### ISSUE TITLE
Padding around elements

### ISSUE THREAD

**Issue by DWL3** [ckcollab/ckcollab#63]
In general padding around elements should be uniform, 100px -- in the process section 50px (since they are back to back around eachother

**Comment by wle8300** [comment]
Fixed in this issue: https://github.com/ckcollab/ckcollab/pull/136

![Screen Shot 2021-08-31 at 4 15 23 PM](https://user-images.githubusercontent.com/150245/131587641-c5122df6-cc9b-4045-af18-dae09b312ea5.png)
