### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by DWL3** [ckcollab/ckcollab#65]
Text needs to come in 200 px on either side
arrow keys should be resized approximately to scale (see img) and brought to level
text display should come up to bottom of monitor (see img) at ~50% opacity

![image](https://user-images.githubusercontent.com/42251227/91615541-ad1caf00-e938-11ea-93d4-2275ed4f80ec.png)

**Comment by Logan-Ruf** [comment]
![image](https://user-images.githubusercontent.com/16579931/93634452-78cf6800-f9a5-11ea-8b3e-73028abc4c84.png)

Even with the darkened background when the text overlaps the bottom of the monitor it does work well. The monitor base draws your eye away from the text. Which isn't something you want to happen while a user is reading. We should either leave it how it is or remove the base from the computer image.

![image](https://user-images.githubusercontent.com/16579931/93636783-5c352f00-f9a9-11ea-9a0b-730428db908a.png)
Here I pushed the text in 55px to match the framing of the rest of the text above. This looks more elegant and uniform.
