### ISSUE TITLE
Link color needs to be set

### ISSUE THREAD

**Issue by DWL3** [ckcollab/ckcollab#66]
![image](https://user-images.githubusercontent.com/42251227/91615768-2b795100-e939-11ea-87f1-ff9486ee3a5d.png)

Link color should be set to either #F06C7C or #60AED9

**Comment by Logan-Ruf** [comment]
What do you think about this?
![image](https://user-images.githubusercontent.com/16579931/92528932-82571400-f1de-11ea-8229-ac7ca7693aad.png)

Inner Link Unvisited
![image](https://user-images.githubusercontent.com/16579931/92529265-0dd0a500-f1df-11ea-9654-8a590bc69b57.png)

Inner Link Visited
![image](https://user-images.githubusercontent.com/16579931/92529304-20e37500-f1df-11ea-980f-4517f2d517d8.png)

**Comment by DWL3** [comment]
I'd say lets go ckc blue for the link, can we try a pink continue button? Blue for both is fine, I just wanna see before I weigh final judgement haha
