### ISSUE TITLE
About section worker-bee blurbs

### ISSUE THREAD

**Issue by DWL3** [ckcollab/ckcollab#84]
![image](https://user-images.githubusercontent.com/42251227/96325050-b4c41000-0fd9-11eb-93f6-47b0d9afeae6.png)

This is not so much an issue I can point to so much as it needs some thinking, but the layout feels disjointed and I can't quite put my finger on it -- anywho, thought it was worth saying and creating an issue despite there being an obvious solution at the moment.

**Comment by wle8300** [comment]
Previously fixed in this PR: https://github.com/ckcollab/ckcollab/pull/136

<img width="1439" alt="Screen Shot 2021-08-31 at 4 10 33 PM" src="https://user-images.githubusercontent.com/150245/131587287-e15d9a15-89b1-4e92-bf26-190037a48eb0.png">
