### ISSUE TITLE
"Let's Work Together" text does not fit on mobile display

### ISSUE THREAD

**Issue by Logan-Ruf** [ckcollab/ckcollab#91]
About Us Page:
![image](https://user-images.githubusercontent.com/16579931/96616575-86835080-12b7-11eb-8115-9b5e8ee4b72b.png)

**Comment by wle8300** [comment]
Previously fixed in this PR: https://github.com/ckcollab/ckcollab/pull/136

<img width="522" alt="Screen Shot 2021-08-31 at 4 08 34 PM" src="https://user-images.githubusercontent.com/150245/131587146-ac27893f-3673-4d70-b4d9-9674e31fe66f.png">
