### ISSUE TITLE
Wrong Font Color for about_us footer (only on mobile)

### ISSUE THREAD

**Issue by Logan-Ruf** [ckcollab/ckcollab#92]
Looks fine when displayed at my normal computer resolution, but when emulating a phone it changes color.
![image](https://user-images.githubusercontent.com/16579931/96616830-afa3e100-12b7-11eb-9442-047abcd42604.png)

**Comment by wle8300** [comment]
Fixed in recent PR

<img width="522" alt="Screen Shot 2021-08-31 at 4 05 46 PM" src="https://user-images.githubusercontent.com/150245/131586923-812a2c4e-d1fb-480a-8aa7-ba18656bd79d.png">
