### ISSUE TITLE
Increase Navigation Between Blog Posts

### ISSUE THREAD

**Issue by Logan-Ruf** [ckcollab/ckcollab#98]
Currently the only navigation, button we have at the top of a blog post takes the user back to the main page. We should have a page that takes the user back to the list of all blog posts.
We could also have more options at the bottom of the page for the latest blog post for the website, and latest blog post for this user.

**Comment by wle8300** [comment]
Fixed in recent PR.

<img width="521" alt="Screen Shot 2021-08-31 at 4 06 55 PM" src="https://user-images.githubusercontent.com/150245/131587010-f2abc466-a6da-40a1-a98f-78a93081b86c.png">
